/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 1
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PIPE = 1,
  aux_sym_quickfix_item_token1 = 2,
  aux_sym_quickfix_item_token2 = 3,
  sym_filename = 4,
  aux_sym_range_token1 = 5,
  anon_sym_col = 6,
  sym_item_type = 7,
  aux_sym_code_block_token1 = 8,
  sym_filetype = 9,
  sym_quickfix_list = 10,
  sym_quickfix_item = 11,
  sym_range = 12,
  sym_code_block = 13,
  aux_sym_quickfix_list_repeat1 = 14,
  alias_sym_col = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PIPE] = "|",
  [aux_sym_quickfix_item_token1] = "quickfix_item_token1",
  [aux_sym_quickfix_item_token2] = "quickfix_item_token2",
  [sym_filename] = "filename",
  [aux_sym_range_token1] = "row",
  [anon_sym_col] = " col ",
  [sym_item_type] = "item_type",
  [aux_sym_code_block_token1] = "content",
  [sym_filetype] = "filetype",
  [sym_quickfix_list] = "quickfix_list",
  [sym_quickfix_item] = "quickfix_item",
  [sym_range] = "range",
  [sym_code_block] = "code_block",
  [aux_sym_quickfix_list_repeat1] = "quickfix_list_repeat1",
  [alias_sym_col] = "col",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym_quickfix_item_token1] = aux_sym_quickfix_item_token1,
  [aux_sym_quickfix_item_token2] = aux_sym_quickfix_item_token2,
  [sym_filename] = sym_filename,
  [aux_sym_range_token1] = aux_sym_range_token1,
  [anon_sym_col] = anon_sym_col,
  [sym_item_type] = sym_item_type,
  [aux_sym_code_block_token1] = aux_sym_code_block_token1,
  [sym_filetype] = sym_filetype,
  [sym_quickfix_list] = sym_quickfix_list,
  [sym_quickfix_item] = sym_quickfix_item,
  [sym_range] = sym_range,
  [sym_code_block] = sym_code_block,
  [aux_sym_quickfix_list_repeat1] = aux_sym_quickfix_list_repeat1,
  [alias_sym_col] = alias_sym_col,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quickfix_item_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quickfix_item_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_range_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_col] = {
    .visible = true,
    .named = false,
  },
  [sym_item_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_block_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_filetype] = {
    .visible = true,
    .named = true,
  },
  [sym_quickfix_list] = {
    .visible = true,
    .named = true,
  },
  [sym_quickfix_item] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_quickfix_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_col] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_col,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead == '|') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead == 'c') ADVANCE(9);
      if (lookahead == '|') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead == '|') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == '!') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '<') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '|') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(18);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_quickfix_item_token1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_quickfix_item_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_filename);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_range_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_col);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_item_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (lookahead == '!') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (lookahead == '!') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_filetype);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 25},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 26},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [aux_sym_range_token1] = ACTIONS(1),
    [anon_sym_col] = ACTIONS(1),
    [sym_filetype] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_quickfix_list] = STATE(12),
    [sym_quickfix_item] = STATE(2),
    [aux_sym_quickfix_list_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_filename] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(5), 1,
      sym_filename,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_quickfix_item,
      aux_sym_quickfix_list_repeat1,
  [11] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_filename,
    STATE(3), 2,
      sym_quickfix_item,
      aux_sym_quickfix_list_repeat1,
  [22] = 3,
    ACTIONS(14), 1,
      aux_sym_code_block_token1,
    ACTIONS(16), 1,
      sym_filetype,
    STATE(8), 1,
      sym_code_block,
  [32] = 2,
    ACTIONS(18), 1,
      aux_sym_range_token1,
    STATE(14), 1,
      sym_range,
  [39] = 2,
    ACTIONS(20), 1,
      anon_sym_PIPE,
    ACTIONS(22), 1,
      sym_item_type,
  [46] = 1,
    ACTIONS(24), 2,
      aux_sym_quickfix_item_token1,
      aux_sym_quickfix_item_token2,
  [51] = 1,
    ACTIONS(26), 2,
      aux_sym_quickfix_item_token1,
      aux_sym_quickfix_item_token2,
  [56] = 1,
    ACTIONS(28), 2,
      aux_sym_quickfix_item_token1,
      aux_sym_quickfix_item_token2,
  [61] = 1,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      sym_filename,
  [66] = 1,
    ACTIONS(32), 1,
      anon_sym_PIPE,
  [70] = 1,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
  [74] = 1,
    ACTIONS(36), 1,
      anon_sym_col,
  [78] = 1,
    ACTIONS(38), 1,
      anon_sym_PIPE,
  [82] = 1,
    ACTIONS(40), 1,
      aux_sym_range_token1,
  [86] = 1,
    ACTIONS(42), 1,
      aux_sym_code_block_token1,
  [90] = 1,
    ACTIONS(44), 1,
      anon_sym_PIPE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 11,
  [SMALL_STATE(4)] = 22,
  [SMALL_STATE(5)] = 32,
  [SMALL_STATE(6)] = 39,
  [SMALL_STATE(7)] = 46,
  [SMALL_STATE(8)] = 51,
  [SMALL_STATE(9)] = 56,
  [SMALL_STATE(10)] = 61,
  [SMALL_STATE(11)] = 66,
  [SMALL_STATE(12)] = 70,
  [SMALL_STATE(13)] = 74,
  [SMALL_STATE(14)] = 78,
  [SMALL_STATE(15)] = 82,
  [SMALL_STATE(16)] = 86,
  [SMALL_STATE(17)] = 90,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quickfix_list, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quickfix_list, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quickfix_list_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quickfix_list_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [14] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [16] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 1),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quickfix_item, 6, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [34] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 4, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_qf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "qf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
